package online.visionacademy.entities;

import java.time.LocalDate;

//table:  students
public class Student implements Identifiable {

    private Long id;//generated by the table
    private Long nationalityId;
    private String firstName;
    private String lastName;
    private LocalDate dob;

    public Student() {
    }

    public Student(Long id, Long nationalityId, String firstName, String lastName, LocalDate dob) {
        this.id = id;
        this.nationalityId = nationalityId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dob = dob;
    }

    public Student(Long nationalityId, String firstName, String lastName, LocalDate dob) {
        this(null, nationalityId, firstName, lastName, dob);
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public Long getNationalityId() {
        return nationalityId;
    }

    public void setNationalityId(Long nationalityId) {
        this.nationalityId = nationalityId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public LocalDate getDob() {
        return dob;
    }

    public void setDob(LocalDate dob) {
        this.dob = dob;
    }

    @Override
    public String toString() {
        return "Student{" + "id=" + id + ", nationalityId=" + nationalityId + ", firstName=" + firstName + ", lastName=" + lastName + ", dob=" + dob + '}';
    }

}
